module.exports = [
	"I ate dinner.",
	"We had a three-course meal.",
	"Brad came to dinner with us.",
	"He loves fish tacos.",
	"In the end, we all felt like we ate too much.",
	"We all agreed; it was a magnificent evening.",
	"I hope that, when I’ve built up my savings, I’ll be able to travel to Mexico.",
	"Did you know that, along with gorgeous architecture, it’s home to the largest tamale?",
	"Wouldn’t it be lovely to enjoy a week soaking up the culture?",
	"Oh, how I’d love to go!",
	"Of all the places to travel, Mexico is at the top of my list.",
	"Would you like to travel with me?",
	"Isn’t language learning fun?",
	"There is so much to understand.",
	"I love learning!",
	"Sentences come in many shapes and sizes.",
	"Nothing beats a complete sentence.",
	"Once you know all the elements, it’s not difficult to pull together a sentence.",
	"I find beautiful language necessary but not sufficient. Few sentences below use prosaic language, but if they do, they acheive beauty by the complexity of their construction, the way the sentence unspools. But if a sentence is only beautiful, and doesn’t stretch for anything more, I feel admiration but not love. After all, there are millions of gorgeous lines of prose, and we only have so much attention.",
	"By wisdom I mean truth, insight, ideas. A sentence functioning as an aphorism. On many of the lists I found around the internet, such as the Buzzfeed list of 51 Beautiful Sentences and the Esquire list of 70 Sentences, this was their main criteria. The language didn’t have to be lovely or ingenious, but they wanted an idea to hoist its flag. For me, wisdom is a secondary consideration after beauty. I would pick a beautiful sentence over a wise sentence any day, because a wise sentence treats language as a mere vehicle while a beautiful sentence elevates language as the primary goal.",
	"No one talks about emotion as a primary consideration for a good sentence. But I look for whether a good sentence elicits sadness or joy, awe or horror. I don’t just want to admire the lines and curves of the prose, I want a string to be plucked deep inside me. An emotionless sentence can look perfectly fine standing on its own, but line them up end to end and they’re the death of a book. One sentiment that is often overlooked in beautiful sentences is humor — a few of the sentences below are quite funny, but I wish I had more.",
	"We were all a little drunk with spring, like the fat bees reeling from flower to flower, and a strange insurrectionary current ran among us.",
	"Men are like armored things, mountainous assemblages of armor and leather, masonry even, which you are told will self-dismantle if you touch the right spot, and out will flow passionate attention.",
	"Once you know all the elements, it’s not difficult to pull together a sentence.",
	"I find beautiful language necessary but not sufficient. Few sentences below use prosaic language, but if they do, they acheive beauty by the complexity of their construction, the way the sentence unspools. But if a sentence is only beautiful, and doesn’t stretch for anything more, I feel admiration but not love. After all, there are millions of gorgeous lines of prose, and we only have so much attention.",
	"By wisdom I mean truth, insight, ideas. A sentence functioning as an aphorism. On many of the lists I found around the internet, such as the Buzzfeed list of 51 Beautiful Sentences and the Esquire list of 70 Sentences, this was their main criteria. The language didn’t have to be lovely or ingenious, but they wanted an idea to hoist its flag. For me, wisdom is a secondary consideration after beauty. I would pick a beautiful sentence over a wise sentence any day, because a wise sentence treats language as a mere vehicle while a beautiful sentence elevates language as the primary goal.",
	"No one talks about emotion as a primary consideration for a good sentence. But I look for whether a good sentence elicits sadness or joy, awe or horror. I don’t just want to admire the lines and curves of the prose, I want a string to be plucked deep inside me. An emotionless sentence can look perfectly fine standing on its own, but line them up end to end and they’re the death of a book. One sentiment that is often overlooked in beautiful sentences is humor — a few of the sentences below are quite funny, but I wish I had more.",
	"We were all a little drunk with spring, like the fat bees reeling from flower to flower, and a strange insurrectionary current ran among us.",
	"Men are like armored things, mountainous assemblages of armor and leather, masonry even, which you are told will self-dismantle if you touch the right spot, and out will flow passionate attention.",
	"Once you know all the elements, it’s not difficult to pull together a sentence.",
	"I find beautiful language necessary but not sufficient. Few sentences below use prosaic language, but if they do, they acheive beauty by the complexity of their construction, the way the sentence unspools. But if a sentence is only beautiful, and doesn’t stretch for anything more, I feel admiration but not love. After all, there are millions of gorgeous lines of prose, and we only have so much attention.",
	"By wisdom I mean truth, insight, ideas. A sentence functioning as an aphorism. On many of the lists I found around the internet, such as the Buzzfeed list of 51 Beautiful Sentences and the Esquire list of 70 Sentences, this was their main criteria. The language didn’t have to be lovely or ingenious, but they wanted an idea to hoist its flag. For me, wisdom is a secondary consideration after beauty. I would pick a beautiful sentence over a wise sentence any day, because a wise sentence treats language as a mere vehicle while a beautiful sentence elevates language as the primary goal.",
	"No one talks about emotion as a primary consideration for a good sentence. But I look for whether a good sentence elicits sadness or joy, awe or horror. I don’t just want to admire the lines and curves of the prose, I want a string to be plucked deep inside me. An emotionless sentence can look perfectly fine standing on its own, but line them up end to end and they’re the death of a book. One sentiment that is often overlooked in beautiful sentences is humor — a few of the sentences below are quite funny, but I wish I had more.",
	"We were all a little drunk with spring, like the fat bees reeling from flower to flower, and a strange insurrectionary current ran among us.",
	"Men are like armored things, mountainous assemblages of armor and leather, masonry even, which you are told will self-dismantle if you touch the right spot, and out will flow passionate attention."
]