module.exports = [
	"https://webcomicms.net/sites/default/files/clipart/130191/camping-pictures-130191-767505.jpg",
	"https://i.insider.com/5d16218921a8610d317c4357?width=750&format=jpeg&auto=webp",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQXuEI7AdLvldsMUI0a7a3SDTQ6Jl3YrFNcTw&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQY3hRKbuS_YllJycutqblVwVSeYabpz12Evg&usqp=CAU",
	"https://www.liligo.com/travel-edition/wp-content/uploads/sites/41/2017/06/Camping.jpg",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQT8vydbfnYh8nM3Onmp5miGHj1RgnDyNfbUQ&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT94KNB1eOlWc0pSCgCNEdNk69-UAwm7yFCrg&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPOdXOpptQiR7dsuWWOkYRHba97TfkgwqWIA&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQgx4V-48AvW3A5vHa4ZF6sXlQsgcj3AqebTA&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRBonbgchaqm88DEkvXQmRzqI9jpkkmdNR6AA&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPjs3PzTub0IdYGs87xE9qORS3ilpyOlVxJQ&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS-40evMLkJTl7p6M5kuLc2fIOk5OHnP9aNkQ&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-cGTujEYUxQJFhgSkHUFsXz9LWmL0LtkPdw&usqp=CAU",
	"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREKcCFuiEp-4RbEnbSxHSSDXYszX1rpSjk_Q&usqp=CAU",
]
